name: Generate Documentation

on:
  push:
    branches:
      - main  # или ваша основная ветка
  pull_request:
    branches:
      - main  # или ваша основная ветка

jobs:
  generate-docs:
    runs-on: ubuntu-latest  # или windows-latest, если вам нужно Windows окружение

    steps:
      # Checkout исходный код
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # укажите вашу версию Python

      # Установка зависимостей для генерации документации
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install sphinx_rtd_theme  # например, для использования темы

      # Генерация документации
      - name: Build documentation
        run: |
          cd docs  # если ваш Sphinx проект в папке docs
          sphinx-build -b html . _build/html  # Генерация документации

      # Публикация документации на GitHub Pages
      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          publish_dir: docs/_build/html  # Путь к сгенерированной документации
