# .github/workflows/ci.yml

name: Windows CI Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build:

    # Запускаем на Windows
    runs-on: windows-latest

    steps:
      # Шаг 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Укажите нужную версию Python

      # Шаг 3. Устанавливаем зависимости
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      # Шаг 4. Запуск тестов
      - name: Run tests 
        run: python -m unittest discover -s tests 
